# Configuration variables - can be overridden via environment variables
BRIDGE_INTERFACE = ENV['BRIDGE_INTERFACE'] || nil  # nil = interactive selection
VM_MEMORY = ENV['VM_MEMORY'] || 8192
VM_CPUS = ENV['VM_CPUS'] || 4
WORKER_COUNT = ENV['WORKER_COUNT'] || 2
NETWORK_BASE = ENV['NETWORK_BASE'] || "10.0.0"

# Box configuration with fallback options
# Set USE_CUSTOM_BOX=false to use public Ubuntu box instead
USE_CUSTOM_BOX = ENV['USE_CUSTOM_BOX'] != 'false'
CUSTOM_BOX = "c_boxes/ubuntu2204-base"
CUSTOM_BOX_VERSION = "0.4.0"
FALLBACK_BOX = "ubuntu/jammy64"  # Ubuntu 22.04 LTS public box

Vagrant.configure("2") do |config|
  config.vm.provider :virtualbox do |v|
    v.memory = VM_MEMORY
    v.cpus = VM_CPUS
  end

  config.vm.provision :shell, privileged: true, path: "../provision/install-common-tools.sh"

  config.vm.define :master do |master|
    if USE_CUSTOM_BOX
      master.vm.box = CUSTOM_BOX
      master.vm.box_version = CUSTOM_BOX_VERSION
    else
      master.vm.box = FALLBACK_BOX
    end
    master.vm.hostname = "master"
    master.vm.network "public_network", bridge: BRIDGE_INTERFACE
    master.vm.network "private_network", ip: "#{NETWORK_BASE}.10"
    # to allow the ip address from above it needs to be added. Check here for details: https://www.virtualbox.org/manual/ch06.html#network_hostonly
    master.vm.provision :shell, privileged: false, path: "../provision/setup-master.sh", env: {"NETWORK_BASE" => NETWORK_BASE}
  end

  (1..WORKER_COUNT).each do |i|
    config.vm.define "worker#{i}" do |worker|
      if USE_CUSTOM_BOX
        worker.vm.box = CUSTOM_BOX
        worker.vm.box_version = CUSTOM_BOX_VERSION
      else
        worker.vm.box = FALLBACK_BOX
      end
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", ip: "#{NETWORK_BASE}.#{i + 10}"
      worker.vm.provision "shell", privileged: false, inline: <<-SHELL
sudo /vagrant/join.sh
# Configure kubelet to use the correct node IP
sudo rm -f /etc/default/kubelet
sudo touch /etc/default/kubelet
echo "KUBELET_EXTRA_ARGS=--node-ip=#{NETWORK_BASE}.#{i + 10}" | sudo tee -a /etc/default/kubelet

sudo systemctl daemon-reload
sudo systemctl restart kubelet
SHELL
    end
  end
end

